// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfbeaktbdnnyndgfucfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmYmVha3RiZG5ueW5kZ2Z1Y2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzA5NTcsImV4cCI6MjA1NzQwNjk1N30.aDdSaju2t3DOU5TXCMRN0iM-qDs6zXkeijTNbF1dZSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);