
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfbeaktbdnnyndgfucfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmYmVha3RiZG5ueW5kZ2Z1Y2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzA5NTcsImV4cCI6MjA1NzQwNjk1N30.aDdSaju2t3DOU5TXCMRN0iM-qDs6zXkeijTNbF1dZSE";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define and export helper functions for storage URLs
export const getStorageUrl = (bucketName: string, filePath: string) => {
  return `${SUPABASE_URL}/storage/v1/object/public/${bucketName}/${filePath}`;
};

// Add manual type definition for donation_requests table
// This is needed until the types file is regenerated
declare module '@supabase/supabase-js' {
  interface Database {
    public: {
      Tables: {
        donation_requests: {
          Row: {
            id: string;
            user_id: string;
            title: string;
            description: string;
            amount: number;
            created_at: string;
            fulfilled: boolean;
          };
          Insert: {
            id?: string;
            user_id: string;
            title: string;
            description: string;
            amount: number;
            created_at?: string;
            fulfilled?: boolean;
          };
          Update: {
            id?: string;
            user_id?: string;
            title?: string;
            description?: string;
            amount?: number;
            created_at?: string;
            fulfilled?: boolean;
          };
        }
      }
    }
  }
}
